default: &default
  adapter: postgresql
  encoding: unicode
  host: 10.1.1.241
  user: postgres
  pool: 10
  password: p0stgr3s

development:
  <<: *default
  database: pits_development

test:
  <<: *default
  database: pits_test

sandbox:
  <<: *default
  database: pits_sandbox

production:
  <<: *default
  database: pits_production