default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: 10

development:
  <<: *default
  database: rails_base_development

test:
  <<: *default
  database: rails_base_test

production:
  <<: *default
  database: rails_base_production