default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  pool: 10

development:
  <<: *default
  database: project_base_development

test:
  <<: *default
  database: project_base_test

sandbox:
  <<: *default
  database: project_base_sandbox

production:
  <<: *default
  database: project_base_production